### ISSUE TITLE
Python Installation Script Does Not Function Normally On Specific Versions of Windows.

### ISSUE THREAD

**Issue by Lafcadia** [lilingfengdev/NitWiki-Script#3]
CUrl was added after Windows 10 build 1803, which means that the Python Installation Script would not support Windows 7, 8, 8.1 and earlier versions of Windows 10.

**Comment by Lafcadia** [comment]
Is this possible to be solved by checking the OS version and automatically downloading the CUrl?

**Comment by aeroidesdev** [comment]
感谢提交此问题
不过此脚本已经废弃，现在已经改为直接生成exe
